name: CI simple

on:
  push:
  issues:
    types:
      - opened
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      - name: Run a one-line script
        run: python --version
      
      - name: run python script
        run: python my-script.py

  deploy:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v4

