name: CI simple

on:
  push:
  pull_request:
  merge_group:
  issues:
    types:
      - opened
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: simple-build
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      - name: Run a one-line script
        run: python --version
      
      - name: run python script
        run: python my-script.py > results.txt

      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: my-results
      
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: ./results.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: run python script
        run: python my-script.py >> $GITHUB_STEP_SUMMARY


  deploy-dev-east:
    needs: test
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       
  deploy-dev-west:
    needs: test
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4

